### ISSUE TITLE
Logo wraps

### ISSUE THREAD

**Issue by mirhamasala** [Subvisual-Academy/subvisuwheel#98]
There are a few options here. We can try:

- Using `font-size` with `vw`

or

- Create media queries

or

- Export the logo as an SVG and use the SVG instead of text

You may also want to look into the property `white-space` if you decide to stick to text.

<img width="315" alt="Screenshot 2022-08-11 at 11 28 39" src="https://user-images.githubusercontent.com/26620750/184104259-b61c6f3c-3c8b-468e-a0d7-7cf48543e26a.png">

**Comment by jreis13** [comment]
This might not be an issue with the new [design](https://www.figma.com/file/36e7nnrNlYQENyigL9sQED/Wheel-of-Fortune?node-id=1024%3A623).

**Comment by mirhamasala** [comment]
@jreis13 Still an issue with the new design.
