### ISSUE TITLE
Logo needs a smaller version too

### ISSUE THREAD

**Issue by mirhamasala** [Subvisual-Academy/subvisuwheel#99]
We're missing a smaller version of the logo. You can pass it as a prop and set default to whatever version you prefer.

Linking this to issue #98 since you may want to tackle them at the same time.

<img width="512" alt="Screenshot 2022-08-11 at 11 31 01" src="https://user-images.githubusercontent.com/26620750/184104627-db455a05-8346-47a3-87d4-bcbab0675b5f.png">

**Comment by mirhamasala** [comment]
It looks like this isn't necessary in the new design.

**Comment by mirhamasala** [comment]
Reopening, following this [thread](https://subvisualuniverse.slack.com/archives/C03KXAJFPHP/p1660220157441509).

**Comment by beasrodrigues24** [comment]
The logo was removed after all, so I assume this issue can be closed?
